### ISSUE TITLE
感谢

### ISSUE THREAD

**Issue by Tiyanki** [Linzertorte/linzertorte.github.io#1]
这个单词表极大地方便了俄语初学者，期待内容更加丰富，请问普通人能为您做些什么呢？

**Comment by Linzertorte** [comment]
这个是用来自动发微博的
https://www.weibo.com/u/7229797725
这都让你发现了。

**Comment by Tiyanki** [comment]
单词网页现在要下载到本地使用了

**Comment by vectorsss** [comment]
感谢！
